const {
  MODE: ENVIRONMENT,
  VITE_API_BASE_PATH: VITE_API_BASE_PATH,
  VITE_GA_MESUREMENT_ID: VITE_GA_MESUREMENT_ID,
} = import.meta.env;

export { ENVIRONMENT, VITE_API_BASE_PATH, VITE_GA_MESUREMENT_ID };
