import { ObjectItem } from "./useCatalogStore";

export const tempObjectData: ObjectItem[] = [
  {
    description: "Современная квартира в новостройке",
    price: 7000000,
    discount: 700000,
    images: [
      "/static/images/home/catalog/img-home-catalog-card-1-2x.webp",
      "/static/images/home/catalog/img-home-catalog-card-2-2x.webp",
    ],
    videoLink: "https://example.com/video1",
    mortgage: true,
    hasSwap: false,
    isCommercial: false,
    isPledge: false,
    isDocumentsGood: true,
    type: "sell",
    visibilityStatus: "active",
    category: "apartment",
    estateAgent: {
      id: "uuid-1234",
      name: "Анна Сергеева",
      avatar: "avatar1.png",
      phone: "+71234567890",
    },
    geoPosition: {
      city: "Москва",
      street: "Тверская",
      houseNumber: 10,
      isInfoHidden: false,
      mapLink: "https://2gis.ru/moscow",
    },
  },
  // Второй объект
  {
    description: "Уютный дом на окраине города",
    price: 12000000,
    discount: 1200000,
    images: [
      "/static/images/home/catalog/img-home-catalog-card-1-2x.webp",
      "/static/images/home/catalog/img-home-catalog-card-2-2x.webp",
    ],
    videoLink: "https://example.com/video2",
    mortgage: false,
    hasSwap: true,
    isCommercial: false,
    isPledge: true,
    isDocumentsGood: false,
    type: "rent",
    visibilityStatus: "active",
    category: "house",
    estateAgent: {
      id: "uuid-5678",
      name: "Михаил Романов",
      avatar: "avatar2.png",
      phone: "+79876543210",
    },
    geoPosition: {
      city: "Санкт-Петербург",
      street: "Невский проспект",
      houseNumber: 28,
      isInfoHidden: false,
      mapLink: "https://2gis.ru/spb",
    },
  },

  // Третий объект
  {
    description: "Промышленный участок под застройку",
    price: 25000000,
    discount: 2500000,
    images: [
      "/static/images/home/catalog/img-home-catalog-card-1-2x.webp",
      "/static/images/home/catalog/img-home-catalog-card-2-2x.webp",
    ],
    videoLink: "https://example.com/video3",
    mortgage: true,
    hasSwap: false,
    isCommercial: true,
    isPledge: false,
    isDocumentsGood: true,
    type: "sell",
    visibilityStatus: "sold",
    category: "land",
    estateAgent: {
      id: "uuid-91011",
      name: "Елена Иванова",
      avatar: "avatar3.png",
      phone: "+71231231212",
    },
    geoPosition: {
      city: "Казань",
      street: "Баумана",
      houseNumber: 15,
      isInfoHidden: true,
      mapLink: "https://2gis.ru/kazan",
    },
  },

  // Четвертый объект
  {
    description: "Офисное помещение в деловом центре",
    price: 15000000,
    discount: 1500000,
    images: [
      "/static/images/home/catalog/img-home-catalog-card-1-2x.webp",
      "/static/images/home/catalog/img-home-catalog-card-2-2x.webp",
    ],
    videoLink: "https://example.com/video4",
    mortgage: false,
    hasSwap: true,
    isCommercial: true,
    isPledge: true,
    isDocumentsGood: false,
    type: "rent",
    visibilityStatus: "checking",
    category: "commercial",
    estateAgent: {
      id: "uuid-121314",
      name: "Дмитрий Кузнецов",
      avatar: "avatar4.png",
      phone: "+70987654321",
    },
    geoPosition: {
      city: "Новосибирск",
      street: "Красный проспект",
      houseNumber: 52,
      isInfoHidden: false,
      mapLink: "https://2gis.ru/novosibirsk",
    },
  },

  // Пятый объект
  {
    description: "Ресторан в историческом центре города",
    price: 20000000,
    discount: 2000000,
    images: [
      "/static/images/home/catalog/img-home-catalog-card-1-2x.webp",
      "/static/images/home/catalog/img-home-catalog-card-2-2x.webp",
    ],
    videoLink: "https://example.com/video5",
    mortgage: true,
    hasSwap: false,
    isCommercial: true,
    isPledge: false,
    isDocumentsGood: true,
    type: "sell",
    visibilityStatus: "active",
    category: "business",
    estateAgent: {
      id: "uuid-151617",
      name: "Елена Воробьева",
      avatar: "avatar5.png",
      phone: "+71012345678",
    },
    geoPosition: {
      city: "Екатеринбург",
      street: "Ленина",
      houseNumber: 34,
      isInfoHidden: true,
      mapLink: "https://2gis.ru/ekaterinburg",
    },
  },
];
